name: cf-grpc-module
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=
  - colorama=
  - numpy=1.22.4
  - pandas=1.4.2
  - geopy=
  - pvlib-python=
  - urllib3=
  - beautifulsoup4=
  - matplotlib=
  - requests=
  - pydantic=
  - jsonpickle=
  - mpld3=
  - pip:
    - grpcio==1.44.0
    - protobuf==3.20.1
    - python-dotenv