name: cf-grpc-module
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=23.0
  - colorama=0.4
  - numpy=1.22
  - pandas=1.4
  - geopy=2.3
  - beautifulsoup4=4.12
  - matplotlib=3.5
  - requests=2.28
  - pydantic=1.10
  - jsonpickle=3.0
  - mpld3=0.5.7
  - pip:
    - grpcio==1.44.0
    - protobuf==3.20.1
    - python-dotenv==0.20.0